added overview of tools
alloftech/alloftech.github.io pull request #10
Opened 2022-09-19 17:40 UTC by shaheen0b111

includes a description of all docker,k8, kind, make components

2022-09-23 11:20 UTC, alloftech requested changes
Please check upon commit suggestions & recommendations

2022-09-23 11:20 UTC, alloftech commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +![Docker Architecture](/assets/images/2022-09-22-00-docker-architecture.png)
Include source of image for giving credits.<br>
Check line 11 for reference

2022-09-23 11:20 UTC, alloftech commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - make is a build tool which ease the creation of executables from source code or executes set of programs/instructions/commands which are written **Makefile**
```suggestion
  - make is a build tool which ease the creation of executables from source code or executes set of programs/instructions/commands which are written in **Makefile**
```

2022-09-23 11:20 UTC, alloftech commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - Detailed [Docker architecture](https://docs.docker.com/get-started/overview/#docker-architecture)
```suggestion
  - To understand docker thoroughly, please check upon this detailed [Docker architecture](https://docs.docker.com/get-started/overview/#docker-architecture) in their documentation.
```

2022-09-23 11:20 UTC, alloftech commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - CLI commands for creating images
Need to use complete sentences for understanding

2022-09-23 11:28 UTC, shaheen0b111 commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - CLI commands for creating images
commit added

2022-09-23 11:31 UTC, sankur-codes commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - CLI commands for creating images
No changes seem to be done yet. Check if pushed.

2022-09-23 13:20 UTC, shaheen0b111 commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +![Docker Architecture](/assets/images/2022-09-22-00-docker-architecture.png)
As required, links to images referred are added along with the source of it

2022-09-23 13:23 UTC, shaheen0b111 commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +  - CLI commands for creating images
Added proper descriptive lines along with necessary links

2022-09-23 18:35 UTC, shaheen0b111 commented on _posts/2022-09-24-01-static-website-on-k8s-local.md
> +![Docker Architecture](/assets/images/2022-09-22-00-docker-architecture.png)
added caption for images

2022-09-24 06:55 UTC, alloftech approved these changes
After changes, LGTM

2022-09-24 06:56 UTC, merged